export const projectData= [
  {
    "id": 1,
    "name": "E-commerce Platform",
    "description": "A full-stack e-commerce solution with React and Node.js",
    "status": "In Progress",
    "progress": 75,
    "startDate": "2024-01-15",
    "endDate": "2024-06-30",
    "budget": 50000,
    "team": ["Alice Johnson", "Bob Smith", "Carol Davis"],
    "technologies": ["React", "Node.js", "MongoDB", "Stripe"],
    "priority": "High"
  },
  {
    "id": 2,
    "name": "Mobile Fitness App",
    "description": "Cross-platform fitness tracking application",
    "status": "Completed",
    "progress": 100,
    "startDate": "2023-11-01",
    "endDate": "2024-02-28",
    "budget": 35000,
    "team": ["David Wilson", "Emma Brown"],
    "technologies": ["React Native", "Firebase", "Redux"],
    "priority": "Medium"
  },
  {
    "id": 3,
    "name": "AI Chatbot Integration",
    "description": "Integrating AI chatbot for customer support",
    "status": "Planning",
    "progress": 20,
    "startDate": "2024-03-01",
    "endDate": "2024-08-15",
    "budget": 75000,
    "team": ["Frank Miller", "Grace Lee", "Henry Chen"],
    "technologies": ["Python", "OpenAI API", "FastAPI", "Docker"],
    "priority": "High"
  },
  {
    "id": 4,
    "name": "Portfolio Website",
    "description": "Personal portfolio website for creative agency",
    "status": "In Progress",
    "progress": 90,
    "startDate": "2024-02-10",
    "endDate": "2024-04-05",
    "budget": 15000,
    "team": ["Ivy Taylor"],
    "technologies": ["Next.js", "Tailwind CSS", "Framer Motion"],
    "priority": "Low"
  },
  {
    "id": 5,
    "name": "Inventory Management System",
    "description": "Enterprise inventory tracking and management",
    "status": "On Hold",
    "progress": 45,
    "startDate": "2023-12-01",
    "endDate": "2024-05-20",
    "budget": 120000,
    "team": ["Jack Anderson", "Karen White", "Leo Martin"],
    "technologies": ["Java", "Spring Boot", "PostgreSQL", "React"],
    "priority": "Medium"
  },
  {
    "id": 6,
    "name": "Social Media Dashboard",
    "description": "Analytics dashboard for social media metrics",
    "status": "Completed",
    "progress": 100,
    "startDate": "2023-09-15",
    "endDate": "2024-01-30",
    "budget": 45000,
    "team": ["Mia Roberts", "Nathan Clark"],
    "technologies": ["Vue.js", "D3.js", "Express.js", "MongoDB"],
    "priority": "Medium"
  },
  {
    "id": 7,
    "name": "Blockchain Wallet",
    "description": "Cryptocurrency wallet with multi-chain support",
    "status": "In Progress",
    "progress": 60,
    "startDate": "2024-01-20",
    "endDate": "2024-09-10",
    "budget": 150000,
    "team": ["Olivia Garcia", "Paul Hernandez", "Quinn Lopez"],
    "technologies": ["Solidity", "Web3.js", "React", "Hardhat"],
    "priority": "High"
  },
  {
    "id": 8,
    "name": "Restaurant Booking System",
    "description": "Online reservation system for restaurants",
    "status": "Planning",
    "progress": 10,
    "startDate": "2024-04-01",
    "endDate": "2024-07-15",
    "budget": 30000,
    "team": ["Rachel Kim", "Samuel Park"],
    "technologies": ["React", "Node.js", "MySQL", "Stripe"],
    "priority": "Medium"
  },
  {
    "id": 9,
    "name": "Weather Monitoring App",
    "description": "Real-time weather data visualization",
    "status": "Completed",
    "progress": 100,
    "startDate": "2023-10-10",
    "endDate": "2024-01-20",
    "budget": 25000,
    "team": ["Thomas Young", "Uma Singh"],
    "technologies": ["React", "Chart.js", "Weather API", "CSS Modules"],
    "priority": "Low"
  },
  {
    "id": 10,
    "name": "Healthcare Portal",
    "description": "Patient management and telemedicine platform",
    "status": "In Progress",
    "progress": 80,
    "startDate": "2023-11-15",
    "endDate": "2024-05-30",
    "budget": 200000,
    "team": ["Victor Adams", "Wendy Baker", "Xavier Cook"],
    "technologies": ["Angular", ".NET", "SQL Server", "Azure"],
    "priority": "High"
  },
  {
    "id": 11,
    "name": "Gaming Platform",
    "description": "Multiplayer online gaming platform",
    "status": "Planning",
    "progress": 5,
    "startDate": "2024-05-01",
    "endDate": "2024-12-31",
    "budget": 300000,
    "team": ["Yvonne Diaz", "Zachary Evans"],
    "technologies": ["Unity", "C#", "Photon", "AWS"],
    "priority": "High"
  },
  {
    "id": 12,
    "name": "Learning Management System",
    "description": "Online course platform with video streaming",
    "status": "In Progress",
    "progress": 70,
    "startDate": "2024-01-08",
    "endDate": "2024-07-20",
    "budget": 85000,
    "team": ["Aaron Fisher", "Bella Gonzalez"],
    "technologies": ["React", "Django", "PostgreSQL", "AWS S3"],
    "priority": "Medium"
  },
  {
    "id": 13,
    "name": "Real Estate Portal",
    "description": "Property listing and virtual tour platform",
    "status": "Completed",
    "progress": 100,
    "startDate": "2023-08-01",
    "endDate": "2024-02-15",
    "budget": 95000,
    "team": ["Caleb Hill", "Diana Irving"],
    "technologies": ["Next.js", "Mapbox", "Strapi", "Cloudinary"],
    "priority": "Medium"
  },
  {
    "id": 14,
    "name": "IoT Home Automation",
    "description": "Smart home device control system",
    "status": "On Hold",
    "progress": 30,
    "startDate": "2023-12-10",
    "endDate": "2024-06-30",
    "budget": 110000,
    "team": ["Ethan James", "Fiona Kelly"],
    "technologies": ["Python", "Raspberry Pi", "MQTT", "React Native"],
    "priority": "Medium"
  },
  {
    "id": 15,
    "name": "Food Delivery App",
    "description": "Mobile app for food ordering and delivery",
    "status": "In Progress",
    "progress": 85,
    "startDate": "2024-02-01",
    "endDate": "2024-05-15",
    "budget": 65000,
    "team": ["George Lewis", "Hannah Moore"],
    "technologies": ["Flutter", "Firebase", "Node.js", "MongoDB"],
    "priority": "High"
  },
  {
    "id": 16,
    "name": "Digital Marketing Tool",
    "description": "Automated social media posting and analytics",
    "status": "Planning",
    "progress": 15,
    "startDate": "2024-04-15",
    "endDate": "2024-10-30",
    "budget": 55000,
    "team": ["Ian Nelson", "Jessica Owens"],
    "technologies": ["Vue.js", "Laravel", "MySQL", "Social APIs"],
    "priority": "Medium"
  }
]