export const fileExplorerData = [
  {
    id: "1",
    name: "src",
    type: "folder",
    children: [
      {
        id: "1-1",
        name: "components",
        type: "folder",
        children: [
          {
            id: "1-1-1",
            name: "Navbar.jsx",
            type: "file",
            extension: "jsx",
            size: "4 KB",
            modifiedAt: "2025-01-10",
          },
          {
            id: "1-1-2",
            name: "Sidebar.jsx",
            type: "file",
            extension: "jsx",
            size: "3 KB",
            modifiedAt: "2025-01-11",
          },
        ],
      },
      {
        id: "1-2",
        name: "pages",
        type: "folder",
        children: [
          {
            id: "1-2-1",
            name: "Home.jsx",
            type: "file",
            extension: "jsx",
            size: "5 KB",
            modifiedAt: "2025-01-12",
          },
          {
            id: "1-2-2",
            name: "Profile.jsx",
            type: "file",
            extension: "jsx",
            size: "6 KB",
            modifiedAt: "2025-01-13",
          },
        ],
      },
      {
        id: "1-3",
        name: "App.jsx",
        type: "file",
        extension: "jsx",
        size: "2 KB",
        modifiedAt: "2025-01-09",
      },
      {
        id: "1-4",
        name: "index.js",
        type: "file",
        extension: "js",
        size: "1 KB",
        modifiedAt: "2025-01-08",
      },
    ],
  },
  {
    id: "2",
    name: "public",
    type: "folder",
    children: [
      {
        id: "2-1",
        name: "index.html",
        type: "file",
        extension: "html",
        size: "2 KB",
        modifiedAt: "2025-01-05",
      },
      {
        id: "2-2",
        name: "favicon.ico",
        type: "file",
        extension: "ico",
        size: "1 KB",
        modifiedAt: "2025-01-04",
      },
    ],
  },
  {
    id: "3",
    name: "package.json",
    type: "file",
    extension: "json",
    size: "1 KB",
    modifiedAt: "2025-01-02",
  },
  {
    id: "4",
    name: "README.md",
    type: "file",
    extension: "md",
    size: "2 KB",
    modifiedAt: "2025-01-01",
  },
];
